### ISSUE TITLE
Set up webpack

### ISSUE THREAD

**Issue by heron2014** [happy-hours/crushlines#11]
- transpile jsx 
- config file

We decided to not use ES6 for now

**Comment by minaorangina** [comment]
* Installed webpack and style/css loaders
```
npm install -g webpack
npm install css-loader [--save-dev]
npm install style-loader [--save-dev]
```
* Setup webpack.config.js
* Add script tag in html for bundle.js
* Run webpack and create your bundle.js file with `$ webpack`
![alt text](https://files.gitter.im/heron2014/fsnj/webpack-success.png)

### Hapi stuff
* Created custom plugin called "Assets" for serving all our frontend assets
* Created custom plugin called "Home" for serving the index page


## Setting up webpack with React
* installed React and ReactDOM
* installed `babel-loader` for webpack
* installed `babel-preset-react` to configure Babel (comes with nothing by default)
* Added babel to `webpack.config.js`, plus preset to set babel up for React

## Setting up React
* app.js: ReactDOM to render onto page

**Comment by heron2014** [comment]
We added scripts to package.json to run webpack and server at the same time without rerunning the script.
